# Generated by Django 4.1.7 on 2023-02-26 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.RegexValidator("^\\d{1,10}$")],
            ),
        ),
    ]
