# Generated by Django 4.1 on 2023-03-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("accounts", "0004_alter_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"City": "france"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.city",
            ),
        ),
    ]
