# Generated by Django 4.1.7 on 2023-02-23 18:33

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(upload_to=job.models.uploaded_image),
        ),
    ]
