# Generated by Django 4.1.7 on 2023-02-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_apply_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="applied_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
