# Generated by Django 4.1 on 2023-03-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_job_job_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="image",
        ),
    ]
